Aktualisierung der oslrd-Init- und Hotplug-Skripte (von openwrt-trunk)

diff --git a/opennet/packages/olsrd/files/olsrd.init b/opennet/packages/olsrd/files/olsrd.init
--- a/opennet/packages/olsrd/files/olsrd.init
+++ b/opennet/packages/olsrd/files/olsrd.init
@@ -1,5 +1,5 @@
 #!/bin/sh /etc/rc.common
-# Copyright (C) 2008-2012 OpenWrt.org
+# Copyright (C) 2008-2013 OpenWrt.org
 
 START=65
 
@@ -13,12 +13,20 @@ PID6=/var/run/olsrd.ipv6.pid
 OLSRD_OLSRD_SCHEMA='ignore:internal config_file:internal DebugLevel=0 AllowNoInt=yes'
 OLSRD_IPCCONNECT_SCHEMA='ignore:internal Host:list Net:list2'
 OLSRD_LOADPLUGIN_SCHEMA='ignore:internal library:internal Host4:list Net4:list2 Host:list Net:list2 Host6:list Net6:list2 Ping:list redistribute:list NonOlsrIf:list name:list lat lon latlon_infile HNA:list2 hosts:list2'
-OLSRD_INTERFACE_SCHEMA='ignore:internal interface:internal AutoDetectChanges:bool'
+OLSRD_INTERFACE_SCHEMA='ignore:internal interface:internal AutoDetectChanges:bool LinkQualityMult:list2'
 OLSRD_INTERFACE_DEFAULTS_SCHEMA='AutoDetectChanges:bool'
 
 T='	'
 N='
 '
+
+log() {
+	logger -t olsrd -p daemon.info -s "${initscript}: $@"
+}
+
+error() {
+	log "ERROR: $@"
+}
 
 validate_varname() {
 	local varname="$1"
@@ -34,9 +42,7 @@ validate_olsrd_option() {
 
 system_config() {
 	local cfg="$1"
-	local cfgt
-	local hostname
-	local latlon
+	local cfgt hostname latlon oldIFS
 
 	config_get cfgt "$cfg" TYPE
 
@@ -48,9 +54,7 @@ system_config() {
 
 	if [ -z "$SYSTEM_LAT" -o -z "$SYSTEM_LON" ]; then
 		config_get latlon "$cfg" latlon
-		IFS=" ${T}${N},"
-		set -- $latlon
-		unset IFS
+		oldIFS="$IFS"; IFS=" ${T}${N},"; set -- $latlon; IFS="$oldIFS"
 		SYSTEM_LAT="$1"
 		SYSTEM_LON="$2"
 	fi
@@ -75,6 +79,7 @@ olsrd_find_config_file() {
 }
 
 warning_invalid_value() {
+	local funcname="warning_invalid_value"
 	local package="$1"
 	validate_varname "$package" || package=
 	local config="$2"
@@ -82,13 +87,11 @@ warning_invalid_value() {
 	local option="$3"
 	validate_varname "$option" || option=
 
-	echo -n "Warning: Invalid value" 1>&2
-
 	if [ -n "$package" -a -n "$config" ]; then
-		echo -n " in option '$package.$config${option:+.}$option'" 1>&2
+		log "$funcname() in option '$package.$config${option:+.}$option', skipped"
+	else
+		log "$funcname() skipped"
 	fi
-
-	echo ", skipped" 1>&2
 
 	return 0
 }
@@ -127,6 +130,7 @@ olsrd_write_option() {
 }
 
 olsrd_write_plparam() {
+	local funcname="olsrd_write_plparam"
 	local param="$1"
 	local cfg="$2"
 	validate_varname "$cfg" || return 1
@@ -134,7 +138,7 @@ olsrd_write_plparam() {
 	validate_varname "$option" || return 1
 	local value="$4"
 	local option_type="$5"
-	local _option
+	local _option oldIFS
 
 	if [ "$option_type" = bool ]; then
 		case "$value" in
@@ -149,23 +153,26 @@ olsrd_write_plparam() {
 		return 1
 	fi
 
+	oldIFS="$IFS"
 	IFS='-_'
 	set -- $option
 	option="$*"
-	unset IFS
+	IFS="$oldIFS"
 	_option="$option"
+
 	if [ "$option" = 'hosts' ]; then
 		set -- $value
 		option="$1"
 		shift
 		value="$*"
 	fi
+
 	if [ "$option" = 'NonOlsrIf' ]; then
 		if validate_varname "$value"; then
 			if network_get_device ifname "$value"; then
-				echo "Info: mdns Interface '$value' ifname '$ifname' found" 1>&2
+				log "$funcname() Info: mdns Interface '$value' ifname '$ifname' found"
 			else
-				echo "Warning: mdns Interface '$value' not found, skipped" 1>&2
+				log "$funcname() Warning: mdns Interface '$value' not found, skipped"
 			fi
 		else
 			warning_invalid_value olsrd "$cfg" "NonOlsrIf"
@@ -179,7 +186,6 @@ olsrd_write_plparam() {
 }
 
 config_update_schema() {
-	unset IFS
 	local schema_varname="$1"
 	validate_varname "$schema_varname" || return 1
 	local command="$2"
@@ -220,43 +226,119 @@ config_update_schema() {
 }
 
 config_write_options() {
-	unset IFS
+	local funcname="config_write_options"
 	local schema="$1"
 	local cfg="$2"
 	validate_varname "$cfg" || return 1
 	local write_func="$3"
 	[ -z "$write_func" ] && output_func=echo
 	local write_param="$4"
-	local schema_entry
-	local option
-	local option_length
-	local option_type
-	local default
-	local value
-	local list_size
-	local list_item
-	local list_value
-	local i
-	local position
 
-	for schema_entry in $schema; do
+	local schema_entry option option_length option_type default value list_size list_item list_value i position speed oldIFS
+	local list_speed_vars="HelloInterval HelloValidityTime TcInterval TcValidityTime MidInterval MidValidityTime HnaInterval HnaValidityTime"
+
+	get_value_for_entry()
+	{
+		local schema_entry="$1"
+
 		default="${schema_entry#*[=]}"
 		[ "$default" = "$schema_entry" ] && default=
 		option="${schema_entry%%[=]*}"
-		IFS=':'
-		set -- $option
-		unset IFS
+
+		oldIFS="$IFS"; IFS=':'; set -- $option; IFS="$oldIFS"
 		option="$1"
 		option_type="$2"
-		validate_varname "$option" || continue
-		[ -z "$option_type" ] || validate_varname "$option_type" || continue
-		[ "$option_type" = internal ] && continue
+
+		validate_varname "$option" || return 1
+		[ -z "$option_type" ] || validate_varname "$option_type" || return 1
+		[ "$option_type" = internal ] && return 1
+
 		config_get value "$cfg" "$option"
+		[ "$option" = "speed" ] && return 1
+
+		return 0
+	}
+
+	already_in_schema()
+	{
+		case " $schema " in
+			*" $1 "*)
+				return 0
+			;;
+			*)
+				return 1
+			;;
+		esac
+	}
+
+	already_in_schema "speed" && {
+		get_value_for_entry "speed"
+
+		if [ 2>/dev/null $value -gt 0 -a $value -le 20 ]; then
+			speed="$value"
+		else
+			log "$funcname() Warning: invalid speed-value: '$value' - allowed integers: 1...20, fallback to 6"
+			speed=6
+		fi
+
+		for schema_entry in $list_speed_vars; do {
+			already_in_schema "$schema_entry" || schema="$schema $schema_entry"
+		} done
+	}
+
+	for schema_entry in $schema; do
+		if [ -n "$speed" ]; then		# like sven-ola freifunk firmware fff-1.7.4
+			case "$schema_entry" in
+				HelloInterval)
+					value="$(( $speed / 2 + 1 )).0"
+				;;
+				HelloValidityTime)
+					value="$(( $speed * 25 )).0"
+				;;
+				TcInterval)	# todo: not fisheye? -> $(( $speed * 2 ))
+					value=$(( $speed / 2 ))
+					[ $value -eq 0 ] && value=1
+					value="$value.0"
+				;;
+				TcValidityTime)
+					value="$(( $speed * 100 )).0"
+				;;
+				MidInterval)
+					value="$(( $speed * 5 )).0"
+				;;
+				MidValidityTime)
+					value="$(( $speed * 100 )).0"
+				;;
+				HnaInterval)
+					value="$(( $speed * 2 )).0"
+				;;
+				HnaValidityTime)
+					value="$(( $speed * 25 )).0"
+				;;
+				*)
+					get_value_for_entry "$schema_entry" || continue
+				;;
+			esac
+
+			is_speed_var()
+			{
+				case " $list_speed_vars " in
+					*" $1 "*)
+						return 0
+					;;
+					*)
+						return 1
+					;;
+				esac
+			}
+
+			is_speed_var "$schema_entry" && option="$schema_entry"
+		else
+			get_value_for_entry "$schema_entry" || continue
+		fi
 
 		if [ -z "$value" ]; then
-			IFS='+'
-			set -- $default
-			unset IFS
+			oldIFS="$IFS"; IFS='+'; set -- $default; IFS="$oldIFS"
 			value=$*
 		elif [ "$value" = '-' -a -n "$default" ]; then
 			continue
@@ -399,6 +481,7 @@ olsrd_write_hna6() {
 }
 
 olsrd_write_loadplugin() {
+	local funcname="olsrd_write_loadplugin"
 	local cfg="$1"
 	validate_varname "$cfg" || return 0
 	local ignore
@@ -417,7 +500,7 @@ olsrd_write_loadplugin() {
 		return 0
 	fi
 	if ! [ -x "/lib/$library" -o -x "/usr/lib/$library" -o -x "/usr/local/lib/$library" ]; then
-		echo "Warning: Plugin library '$library' not found, skipped" 1>&2
+		log "$funcname() Warning: Plugin library '$library' not found, skipped"
 		return 0
 	fi
 
@@ -462,6 +545,7 @@ olsrd_write_loadplugin() {
 }
 
 olsrd_write_interface() {
+	local funcname="olsrd_write_interface"
 	local cfg="$1"
 	validate_varname "$cfg" || return 0
 	local ignore
@@ -474,13 +558,20 @@ olsrd_write_interface() {
 
 	ifnames=
 	config_get interfaces "$cfg" interface
+
 	for interface in $interfaces; do
 		if validate_varname "$interface"; then
 			if network_get_device IFNAME "$interface"; then
 				ifnames="$ifnames \"$IFNAME\""
 				ifsglobal="$ifsglobal $IFNAME"
+			elif network_get_physdev IFNAME "$interface"; then
+				local proto="$(uci -q get network.${interface}.proto)"
+				if [ "$proto" = "static" -o "$proto" = "none" ]; then
+					ifnames="$ifnames \"$IFNAME\""
+					ifsglobal="$ifsglobal $IFNAME"
+				fi
 			else
-				echo "Warning: Interface '$interface' not found, skipped" 1>&2
+				log "$funcname() Warning: Interface '$interface' not found, skipped"
 			fi
 		else
 			warning_invalid_value olsrd "$cfg" "interface"
@@ -551,14 +642,51 @@ olsrd_write_config() {
 	return 0
 }
 
-olsrd_setup_smartgw_rules() {
-	# Check if ipip is installed
-	[ ! -e /etc/modules.d/[0-9]*-ipip ] && echo "Warning: kmod-ipip is missing. SmartGateway will not work until you install it."
+get_wan_ifnames()
+{
+	local wanifnames word catch_next
 
-	wanifnames=$(ip r l e 0/0 t all | sed -e 's/^.* dev //' |cut -d " " -f 1 | sort | uniq)
-	nowan=0
+	which ip >/dev/null || return 1
+
+	set -- $( ip route list exact 0.0.0.0/0 table all )
+	for word in $*; do
+		case "$word" in
+			dev)
+				catch_next="true"
+			;;
+			*)
+				[ -n "$catch_next" ] && {
+					case "$wanifnames" in
+						*" $word "*)
+						;;
+						*)
+							wanifnames="$wanifnames $word "
+						;;
+					esac
+
+					catch_next=
+				}
+			;;
+		esac
+	done
+
+	echo "$wanifnames"
+}
+
+olsrd_setup_smartgw_rules() {
+	local funcname="olsrd_setup_smartgw_rules"
+	# Check if ipip is installed
+	[ -e /etc/modules.d/[0-9]*-ipip ] || {
+		log "$funcname() Warning: kmod-ipip is missing. SmartGateway will not work until you install it."
+		return 1
+	}
+
+	local wanifnames="$( get_wan_ifnames )"
+
 	if [ -z "$wanifnames" ]; then
 		nowan=1
+	else
+		nowan=0
 	fi
 
 	IP4T=$(which iptables)
@@ -577,7 +705,7 @@ olsrd_setup_smartgw_rules() {
 	while $IP4T -t nat -D postrouting_rule -o tnl_+ -j MASQUERADE 2> /dev/null; do :;done
 
 	if [ "$smartgateway" == "yes" ]; then
-		echo "Notice: Inserting firewall rules for SmartGateway"
+		log "$funcname() Notice: Inserting firewall rules for SmartGateway"
 		if [ ! "$smartgatewayuplink" == "none" ]; then
 			if [ "$smartgatewayuplink" == "ipv4" ]; then
 				# Allow everything to be forwarded to tnl_+ and use NAT for it
@@ -604,9 +732,9 @@ olsrd_setup_smartgw_rules() {
 					$IP6T -I input_rule -i $IFACE -p 4 -j ACCEPT
 				done
 			else
+				$IP4T -t nat -I postrouting_rule -o tnl_+ -j MASQUERADE
 				for IPT in $IP4T $IP6T; do
 					$IPT -I forwarding_rule -o tnl_+ -j ACCEPT
-					$IPT -t nat -I postrouting_rule -o tnl_+ -j MASQUERADE
 					if [ "$nowan"="0" ]; then
 						for IFACE in $wanifnames; do
 							$IPT -A forwarding_rule -i tunl0 -o $IFACE -j ACCEPT
@@ -619,10 +747,6 @@ olsrd_setup_smartgw_rules() {
 			fi
 		fi
 	fi
-}
-
-error() {
-	echo "${initscript}:" "$@" 1>&2
 }
 
 start() {
@@ -640,7 +764,7 @@ start() {
 		olsrd_update_schema "list" "$@"
 	}
 
-	. "${IPKG_INSTROOT:-}/lib/functions/network.sh"
+	. /lib/functions/network.sh
 
 	config_load olsrd
 	reset_cb
@@ -674,14 +798,14 @@ start() {
 
 		SERVICE_PID_FILE="$PID6"
 		if service_check /usr/sbin/olsrd; then
-			error "there already is an IPv6 instance of olsrd running ($(cat $PID6)), not starting."
+			error "there is already an IPv6 instance of olsrd running (pid: '$(cat $PID6)'), not starting."
 		else
 			service_start /usr/sbin/olsrd -f /var/etc/olsrd.conf.ipv6 -nofork
 		fi
 
 		SERVICE_PID_FILE="$PID"
 		if service_check /usr/sbin/olsrd; then
-			error "there already is an IPv4 instance of olsrd running ($(cat $PID)), not starting."
+			error "there is already an IPv4 instance of olsrd running (pid: '$(cat $PID)'), not starting."
 		else
 			service_start /usr/sbin/olsrd -f /var/etc/olsrd.conf.ipv4 -nofork
 		fi
@@ -697,12 +821,16 @@ start() {
 
 		SERVICE_PID_FILE="$PID"
 		if service_check /usr/sbin/olsrd; then
-			error "there already is an IPv4 instance of olsrd running ($(cat $PID)), not starting."
+			error "there is already an IPv4 instance of olsrd running (pid: '$(cat $PID)'), not starting."
 			return 1
 		else
 			service_start /usr/sbin/olsrd -f "$OLSRD_CONFIG_FILE" -nofork
+			service_check /usr/sbin/olsrd || {
+				log "startup-error: check via: '/usr/sbin/olsrd -f \"$OLSRD_CONFIG_FILE\" -nofork'"
+			}
 		fi
 	fi
+
 	olsrd_setup_smartgw_rules
 }
 
