on-monitoring: wireless_signal_ranges-Plugin mit verbessertem Umgang für fehlerhaften Aufruf

diff --git a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_ranges_ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_ranges_
--- a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_ranges_
+++ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_ranges_
@@ -121,7 +121,8 @@ case "$ACTION" in
 		do_fetch
 		;;
 	*)
-		echo >&2 "Invalid action (valid: config)"
+		echo >&2 "Invalid action (valid: config / autoconf / suggest / <empty>)"
 		echo >&2
+		exit 2
 		;;
 esac
