on-monitoring: wireless_signal_noise-Plugin für munin's DIRTYCONFIG vorbereitet

diff --git a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
--- a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
+++ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
@@ -70,26 +70,50 @@ get_wifi_device_from_suffix() {
 }
 
 
+do_config() {
+	local wifi
+	wifi=$(get_wifi_device_from_suffix)
+	[ -z "$wifi" ] && echo >&2 "Missing wifi: $wifi" && return 1
+	echo "graph_title Wireless signal quality - $wifi"
+	echo "graph_args --upper-limit 0"
+	echo "graph_vlabel Signal and noise [dBm]"
+	echo "graph_category network"
+	echo "graph_info This graph shows the signal and noise for all wifi peers"
+	echo "noise.label Noise floor"
+	echo "noise.draw LINE"
+	# sub graphs for all peers
+	get_wifi_peers "$wifi" | while read mac signal; do
+		fieldname=$(clean_fieldname "peer_${mac}")
+		peer=$(get_ip_for_mac "$mac")
+		echo "signal_${fieldname}.label $peer"
+		echo "signal_${fieldname}.draw LINE"
+	done
+}
+
+
+do_fetch() {
+	local wifi
+	local peer_data
+	local noise
+	wifi=$(get_wifi_device_from_suffix)
+	[ -z "$wifi" ] && echo >&2 "Missing wifi: $wifi" && return 1
+	peer_data=$(get_wifi_peers "$wifi")
+	echo "$peer_data" | while read mac signal; do
+		# ignore empty datasets
+		[ -z "$signal" ] && continue
+		fieldname=$(clean_fieldname "peer_${mac}")
+		echo "signal_${fieldname}.value $signal"
+	done
+	noise=$(get_wifi_noise "$wifi")
+	echo "noise.value ${noise:-U}"
+}
+
+
 ACTION="${1:-}"
 
 case "$ACTION" in
 	config)
-		wifi=$(get_wifi_device_from_suffix)
-		[ -z "$wifi" ] && echo >&2 "Missing wifi: $wifi" && exit 1
-		echo "graph_title Wireless signal quality - $wifi"
-		echo "graph_args --upper-limit 0"
-		echo "graph_vlabel Signal and noise [dBm]"
-		echo "graph_category network"
-		echo "graph_info This graph shows the signal and noise for all wifi peers"
-		echo "noise.label Noise floor"
-		echo "noise.draw LINE"
-		# sub graphs for all peers
-		get_wifi_peers "$wifi" | while read mac signal; do
-			fieldname=$(clean_fieldname "peer_${mac}")
-			peer=$(get_ip_for_mac "$mac")
-			echo "signal_${fieldname}.label $peer"
-			echo "signal_${fieldname}.draw LINE"
-		done
+		do_config
 		;;
 	autoconf)
 		if [ -z "$(get_wifi_interfaces)" ]; then
@@ -104,17 +128,7 @@ case "$ACTION" in
 		done
 		;;
 	"")
-		wifi=$(get_wifi_device_from_suffix)
-		[ -z "$wifi" ] && echo >&2 "Missing wifi: $wifi" && exit 1
-		peer_data=$(get_wifi_peers "$wifi")
-		echo "$peer_data" | while read mac signal; do
-			# ignore empty datasets
-			[ -z "$signal" ] && continue
-			fieldname=$(clean_fieldname "peer_${mac}")
-			echo "signal_${fieldname}.value $signal"
-		done
-		noise=$(get_wifi_noise "$wifi")
-		echo "noise.value ${noise:-U}"
+		do_fetch
 		;;
 	*)
 		echo >&2 "Invalid action (valid: config)"
