on-monitoring: wireless_signal_noise-Plugin mit verbessertem Umgang für fehlerhaften Aufruf

diff --git a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
--- a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
+++ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
@@ -132,7 +132,8 @@ case "$ACTION" in
 		do_fetch
 		;;
 	*)
-		echo >&2 "Invalid action (valid: config)"
+		echo >&2 "Invalid action (valid: config / suggest / autoconf / <empty>)"
 		echo >&2
+		exit 2
 		;;
 esac
