Monitoring: wireless_signal_noise_ toleriert fehlendes Interface

diff --git a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
--- a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
+++ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_signal_noise_
@@ -75,6 +75,7 @@ ACTION="${1:-}"
 case "$ACTION" in
 	config)
 		wifi=$(get_wifi_device_from_suffix)
+		[ -z "$wifi" ] && echo >&2 "Missing wifi: $wifi" && exit 1
 		echo "graph_title Wireless signal quality - $wifi"
 		echo "graph_args --upper-limit 0"
 		echo "graph_vlabel Signal and noise [dBm]"
@@ -101,6 +102,7 @@ case "$ACTION" in
 		;;
 	"")
 		wifi=$(get_wifi_device_from_suffix)
+		[ -z "$wifi" ] && echo >&2 "Missing wifi: $wifi" && exit 1
 		peer_data=$(get_wifi_peers "$wifi")
 		echo "$peer_data" | while read mac signal; do
 			# ignore empty datasets
