on-monitoring: Plugin wireless_channel_active_ funktioniert auch mit "iw"

diff --git a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_channel_active_ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_channel_active_
--- a/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_channel_active_
+++ b/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/wireless_channel_active_
@@ -13,22 +13,38 @@
 #%# family=auto
 
 
+
+
+
+
+
 set -eu
 
+if which iwinfo >/dev/null; then
+	# "iwinfo" has a stable output format but is only available on OpenWrt
+	get_physical_interfaces() { iwinfo | sed -n 's/^.*PHY name: \+\(.*\)$/\1/p'; }
+	get_physical_interface_current_channel() { iwinfo "$1" info \
+		| grep Channel | sed 's/^.*Channel: \+\([0-9]\+\) .*$/\1/'; }
+	get_physical_interfaces_channel_descriptions() {
+		# return: CHANNEL CHANNEL_DESCRIPTION
+		# e.g.: "104 5.520 GHz (Channel 104)"
+		iwinfo "$1" freqlist | sed 's/^[^0-9]*//' \
+			| sed 's/^.*Channel \+\([0-9]\+\).*$/\1 \0/'; }
+else
+	# "iw" is available everywhere - but its output format is not recommended for non-humans
+	get_physical_interfaces() { iw list | awk '/^\w/ {print $2}'; }
+	get_physical_interface_current_channel() { iw dev | awk '
+		/^\w+#/ { phy_name=gensub("#", "", 1, $1); }
+		/channel/ { if (phy_name == "phy0") print($2); }'; }
+	get_physical_interfaces_channel_descriptions() {
+		# example input: "* 5680 MHz [136]"
+		# return: CHANNEL CHANNEL_DESCRIPTION
+		# e.g.: "136 5680 MHz [136]"
+		iw phy phy0 channels | awk '
+			/\*/ { chan_num=gensub("^.*\\[", "", 1, gensub("\\].*$", "", 1, $0));
+				print(chan_num, $2, $3, $4); }'; }
+fi
 
-get_physicial_interfaces() {
-	iwinfo | grep "PHY name:" | sed 's/^.*PHY name: \+\(.*\)$/\1/'
-}
-
-get_physicial_interface_current_channel() {
-	iwinfo "$1" info | grep Channel | sed 's/^.*Channel: \+\([0-9]\+\) .*$/\1/'
-}
-
-get_physical_interfaces_channel_descriptions() {
-	# return: CHANNEL CHANNEL_DESCRIPTION
-	# e.g.: "104 5.520 GHz (Channel 104)"
-	iwinfo "$1" freqlist | sed 's/^[^0-9]*//' | sed 's/^.*Channel \+\([0-9]\+\).*$/\1 \0/'
-}
 
 get_selected_physical_interface() {
 	# The physical interface name should be safe (phyX) and needs no cleanup.
@@ -40,7 +56,7 @@ get_selected_physical_interface() {
 do_config() {
 	local phy
 	phy=$(get_selected_physical_interface)
-	[ -z "$phy" ] && echo >&2 "Missing wireless PHY: $phy" && return 1
+	[ -z "$phy" ] && echo >&2 "Missing wireless PHY" && return 1
 	echo "graph_title Wireless channel usage - $phy"
 	echo "graph_args --base 1000 -r --lower-limit 0 --upper-limit 100"
 	echo "graph_vlabel Channel usage by time in percent"
@@ -60,8 +76,8 @@ do_fetch() {
 	local phy
 	local current_channel
 	phy=$(get_selected_physical_interface)
-	[ -z "$phy" ] && echo >&2 "Missing wireless PHY: $phy" && return 1
-	current_channel=$(get_physicial_interface_current_channel "$phy")
+	[ -z "$phy" ] && echo >&2 "Missing wireless PHY" && return 1
+	current_channel=$(get_physical_interface_current_channel "$phy")
 	get_physical_interfaces_channel_descriptions "$phy" | while read -r channel description; do
 		[ "$current_channel" = "$channel" ] && value=1 || value=0
 		echo "channel_${channel}.value $value"
@@ -77,14 +93,14 @@ case "$ACTION" in
 		[ "${MUNIN_CAP_DIRTYCONFIG:-0}" = 1 ] && do_fetch
 		;;
 	autoconf)
-		if [ -z "$(get_physicial_interfaces)" ]; then
+		if [ -z "$(get_physical_interfaces)" ]; then
 			echo "no (no wifi interfaces found)"
 		else
 			echo "yes"
 		fi
 		;;
 	suggest)
-		get_physicial_interfaces
+		get_physical_interfaces
 		;;
 	"")
 		do_fetch
